### ISSUE TITLE
/sidekiq is not a protected route

### ISSUE THREAD

**Issue by thoresuenert** [dokku/dokku-api#11]
when i visit `dokku-api.mydomain.com/sidekiq`, i can see the sidekiq web frontend.

No login needed, is it expected behavior?

**Comment by beydogan** [comment]
@thoresuenert thanks for reporting, no it is not expected behavior, it wasn't implemented. I've just pushed https://github.com/dokku/dokku-api/commit/6596fe9602036c15561aaaf341ab88c215fd0528 and fixed.

See https://github.com/dokku/dokku-api#sidekiq-web for more details

**Comment by liamcottle** [comment]
I assume the readme should say `SIDEKIQ_USER` instead of `SIDEKIQ_ADMIN` since config uses `ENV["SIDEKIQ_USER"]` 😆

**Comment by beydogan** [comment]
@liamcottle yes yes, I realized that :smile: thank you.
