### ISSUE TITLE
Rake error

### ISSUE THREAD

**Issue by internetstyle** [dokku/dokku-api#7]
I'm getting error when trying generate api keys:

root@prod:~# dokku run dokku-api rake keys:generate
bundler: failed to load command: rake (/usr/local/bin/rake)
Gem::Exception: can't find executable rake
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:408:in `block in replace_bin_path'
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:434:in `block in replace_bin_path'
  /usr/local/bin/rake:22:in `<top (required)>'

What could be happening? Thanks.

**Comment by beydogan** [comment]
I just realized I didn't ignore development Dockerfile from git and it was causing Dokku to use Dockerfile deployment instead of regular ruby buildpack. 

I fixed the issue, you should be fine after pulling latest code and deploying again.

Please let me know if the issue continues.

**Comment by internetstyle** [comment]
Now it worked. Thank you.

**Comment by internetstyle** [comment]
I updated, I generated keys, but now the connection is refused:

`curl: (7) Failed to connect to 45.*** port 42143: Connection refused`

 What could I have done wrong? Thanks

**Comment by beydogan** [comment]
Can you paste the output of `dokku config dokku-api`?

**Comment by internetstyle** [comment]
```
=====> dokku-api config vars
DATABASE_URL:                postgres://postgres:ad4070d4670c3869c906106fd62866a5@dokku-postgres-dokku-api:5432/dokku_api
DOKKU_APP_RESTORE:           1
DOKKU_APP_TYPE:              herokuish
DOKKU_DOCKERFILE_ENTRYPOINT: ENTRYPOINT ["bundler", "exec"]
DOKKU_NGINX_PORT:            80
DOKKU_PROXY_PORT_MAP:        http:80:5000
REDIS_URL:                   redis://dokku-api:e657936300e6a9774fb0c0a9cf5868afc6f3eecab7ed508480604ee59e4b7e7b@dokku-redis-dokku-api:6379
```

**Comment by internetstyle** [comment]
In default port (80) connect, but response is empty:

```
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 06 Jan 2018 12:06:06 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
X-Content-Type-Options: nosniff

[]
```

**Comment by beydogan** [comment]
Some of config related ports left from Dockerfile deployment. Try running following to unset and fix ports;
`dokku config:unset dokku-api  DOKKU_DOCKERFILE_ENTRYPOINT DOKKU_NGINX_PORT DOKKU_PROXY_PORT_MAP`

Empty response might mean there are no command created yet.

**Comment by internetstyle** [comment]
Thanks for reply.

Sorry to bother with this question, but I still have an error. I understood that I had to register the commands, but now I get this error:

`{"id":4,"token":"24225b3762115ef70a90bf4b1ec805d47be7448e54d344bfbbbdfe8b7e51ceb5","command":"apps","created_at":"2018-01-06T15:53:22+00:00","ran_at":"2018-01-06T15:53:22+00:00","callback_url":null,"result_data":{"ok":false,"output":"No such file or directory - connect(2) for /var/run/dokku-daemon/dokku-daemon.sock"}}`

I installed dokku-daemon according to the instructions. What can it be?

**Comment by internetstyle** [comment]
```
find / -type f -name "dokku-daemon*"
/usr/bin/dokku-daemon
/root/dokku-daemon/init/dokku-daemon.service
/root/dokku-daemon/init/dokku-daemon.conf
/root/dokku-daemon/bin/dokku-daemon
/etc/systemd/system/dokku-daemon.service
```
dokku-daemon.sock really not exists.

**Comment by beydogan** [comment]
That's related to dokku-daemon but its probably a permissions issue. Whats the owner user of `dokku-daemon.sock`? Make sure its `dokku`

**Comment by beydogan** [comment]
Ignore my previous reply, I misread. Try to install my daemon written in golang: https://github.com/beydogan/dokku-daemon-go

**Comment by beydogan** [comment]
I'll close this. Feel free to open an issue to docker-daemon project if you cannot resolve the issue you mentioned.
