### ISSUE TITLE
Commands with string length larger 50 characters result in Postgresql error

### ISSUE THREAD

**Issue by michaelklopf** [dokku/dokku-api#8]
Hello,

we learned that commands larger than 50 characters, e.g., `"command": "clone testproject https://github.com/test/testproject.git",` result in an error. We use Dokku Clone (https://github.com/crisward/dokku-clone) to setup our applications.

Test wise, we manually set the command property length to 255 at https://github.com/dokku/dokku-api/blob/master/models/command.rb and changed the postgres table to accomodate these changes.

Apparently, the DataMapper defaulted to 50 characters for the database table, because that's how it looked like.

Changing the database helped to fix to the problem. So, preventing the DataMapper default to come through should fix the problem, but we are no Ruby experts.

Kind regards,

Michael

**Comment by beydogan** [comment]
Thank you for reporting @michaelklopf 

I will fix this shortly.
