### ISSUE TITLE
Authentication Not Required?

### ISSUE THREAD

**Issue by liamcottle** [dokku/dokku-api#9]
[Readme states](https://github.com/dokku/dokku-api#authentication) that the headers `Api-Key` and `Api-Secret` are required. However, requesting any endpoint without them is successful and doesn't output an unauthorized error.

**Comment by liamcottle** [comment]
Authentication is now working as intended, Cheers!

**Comment by beydogan** [comment]
This is what happens when you don't have specs :) thanks for reporting.
